import { describe, it, expect, afterAll } from 'vitest';
import { run } from '../src/index.js';
import { readFileSync, existsSync, rmSync } from 'node:fs';
import { join } from 'node:path';

const outputDir = join(import.meta.dirname, '..', '.test-output');
const xmlDir = join(import.meta.dirname, '..', 'example', 'xml');

afterAll(() => {
  if (existsSync(outputDir)) {
    rmSync(outputDir, { recursive: true });
  }
});

describe('integration', () => {
  it('generates grouped output from example XML', async () => {
    await run({
      directory: xmlDir,
      output: join(outputDir, 'api-%s.md'),
      groups: true,
      pages: true,
      anchors: true,
      quiet: true,
    });

    // Check all expected files were created
    const expectedFiles = [
      'api-bicycle.md',
      'api-mountainbike.md',
      'api-racingbike.md',
    ];

    for (const file of expectedFiles) {
      const filepath = join(outputDir, file);
      expect(existsSync(filepath), `${file} should exist`).toBe(true);

      const content = readFileSync(filepath, 'utf8');
      expect(content.length).toBeGreaterThan(0);
    }
  });

  it('generates page output', async () => {
    const expectedPages = [
      'page-changelog.md',
      'page-overview.md',
    ];

    for (const file of expectedPages) {
      const filepath = join(outputDir, file);
      expect(existsSync(filepath), `${file} should exist`).toBe(true);

      const content = readFileSync(filepath, 'utf8');
      expect(content.length).toBeGreaterThan(0);
    }
  });

  it('output contains expected class documentation', async () => {
    const content = readFileSync(join(outputDir, 'api-bicycle.md'), 'utf8');

    // Should contain the Bicycle class
    expect(content).toContain('Bicycle');

    // Should contain member functions
    expect(content).toContain('PedalHarder');
    expect(content).toContain('RingBell');

    // Should contain anchors
    expect(content).toContain('{#classtransport_1_1Bicycle}');

    // Should contain description text
    expect(content).toContain('Standard bicycle class');
  });

  it('generates single file output', async () => {
    const singleOutput = join(outputDir, 'single-api.md');

    await run({
      directory: xmlDir,
      output: singleOutput,
      quiet: true,
    });

    expect(existsSync(singleOutput)).toBe(true);
    const content = readFileSync(singleOutput, 'utf8');

    // Should contain the Moxygen footer
    expect(content).toContain('Generated by [Moxygen]');

    // Should contain classes from all groups
    expect(content).toContain('Bicycle');
    expect(content).toContain('MountainBike');
    expect(content).toContain('RacingBike');
  });
});
