version: 2
updates:
  - package-ecosystem: npm
    directories:
      - "/"
      - "/docs"
    schedule:
      interval: weekly
    groups:
      npm-versions:
        applies-to: version-updates
        patterns:
          - "*"
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"
