/**
 * Original work Copyright (c) 2016 Philippe FERDINAND
 * Modified work Copyright (c) 2016 Kam Low
 *
 * @license MIT
 */

import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { toArray, toFilteredArray, filterChildren } from './compound.js';
import { writeCompound } from './helpers.js';
import { log } from './logger.js';
import { loadIndex } from './parser.js';
import * as templates from './templates.js';
import type { Compound, Filters, MoxygenOptions } from './types.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

export const defaultFilters: Filters = {
  members: [
    'define',
    'enum',
    'func',
    'var',
    'property',
    'public-attrib',
    'public-func',
    'public-static-attrib',
    'public-static-func',
    'protected-attrib',
    'protected-func',
    'signal',
    'public-slot',
    'protected-slot',
    'public-type',
    'private-attrib',
    'private-func',
    'private-slot',
    'private-static-func',
  ],
  compounds: [
    'namespace',
    'class',
    'struct',
    'union',
    'typedef',
    'interface',
    'enum',
  ],
};

export const defaultOptions: MoxygenOptions = {
  directory: '',
  output: 'api.md',
  groups: false,
  classes: false,
  pages: false,
  noindex: false,
  anchors: true,
  htmlAnchors: false,
  language: 'cpp',
  templates: 'templates',
  quiet: false,
  filters: defaultFilters,
};

/**
 * Parse Doxygen XML and render Markdown output.
 */
export async function run(options: Partial<MoxygenOptions> & { directory: string }): Promise<void> {
  const opts: MoxygenOptions = { ...defaultOptions, ...options };

  if (!opts.filters) {
    opts.filters = defaultFilters;
  }

  // Determine output filename
  if (!options.output) {
    opts.output = opts.classes || opts.groups
      ? 'api_%s.md'
      : 'api.md';
  }

  if ((opts.classes || opts.groups) && !opts.output.includes('%s')) {
    throw new Error(
      "The `output` file parameter must contain '%s' for group or class name " +
      'substitution when `groups` or `classes` are enabled.',
    );
  }

  // Resolve templates directory
  if (!options.templates) {
    opts.templates = join(__dirname, '..', 'templates', opts.language);
  }

  log.init(opts);

  // Load templates
  templates.registerHelpers(opts);
  templates.load(opts.templates);

  // Parse XML
  const { root, references } = await loadIndex(opts);

  // Output groups
  if (opts.groups) {
    const groups = toArray(root, 'compounds', 'group') as Compound[];
    if (!groups.length) {
      throw new Error(
        'You have enabled `groups` output, but no groups were located in your doxygen XML files.',
      );
    }

    for (const group of groups) {
      filterChildren(group, opts.filters, group.id);
      const compounds = toFilteredArray(group, 'compounds');
      compounds.unshift(group);
      writeCompound(group, templates.renderArray(compounds), references, opts);
    }
  } else if (opts.classes) {
    const rootCompounds = toArray(root, 'compounds', 'namespace') as Compound[];
    if (!rootCompounds.length) {
      throw new Error(
        'You have enabled `classes` output, but no classes were located in your doxygen XML files.',
      );
    }

    for (const comp of rootCompounds) {
      filterChildren(comp, opts.filters);
      const compounds = toFilteredArray(comp);
      writeCompound(comp, [templates.render(comp)], references, opts);
      for (const e of compounds) {
        filterChildren(e, opts.filters);
        writeCompound(e, [templates.render(e)], references, opts);
      }
    }
  } else {
    // Single file output
    filterChildren(root, opts.filters);
    const compounds = toFilteredArray(root, 'compounds');
    if (!opts.noindex) {
      compounds.unshift(root);
    }
    const contents = templates.renderArray(compounds);
    contents.push('Generated by [Moxygen](https://sourcey.com/code/moxygen)');
    writeCompound(root, contents, references, opts);
  }

  // Pages
  if (opts.pages) {
    const pages = toArray(root, 'compounds', 'page') as Compound[];
    if (!pages.length) {
      throw new Error(
        'You have enabled `pages` output, but no pages were located in your doxygen XML files.',
      );
    }

    for (const page of pages) {
      const compounds = toFilteredArray(page, 'compounds');
      compounds.unshift(page);
      writeCompound(page, templates.renderArray(compounds), references, opts);
    }
  }
}

export { loadIndex } from './parser.js';
export type { MoxygenOptions, Compound, Member, References } from './types.js';
